[theme]
primaryColor = "#ffffff"
backgroundColor = "#ec009d7a"
secondaryBackgroundColor = "#7d365ff5"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "hidden"

[ui]
hideTopBar = true
